version: '3'

services:
  mysql:
    image: mysql:8
    container_name: "dev-pyramid-mysql"
    environment:
      MYSQL_DATABASE: db_wa
      MYSQL_USER: db_wa
      MYSQL_PASSWORD: "123qweASD"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - ./services/pyramid/database/dump/backup-latest.sql:/docker-entrypoint-initdb.d/backup-latest.sql

  app:
    build: ./services/pyramid
    container_name: dev-pyramid-app
    depends_on:
      - mysql
    restart: unless-stopped
    tty: true
    develop:
      watch:
        - action: sync
          path: ./services/pyramid
          target: /var/www
          ignore:
            - /pyramid/vendor
        - action: sync+restart
          path: ./services/pyramid/composer.json
          target: /var/www/composer.json
    command: >
      bash -c "mkdir -p storage/framework/{sessions,views,cache} &&
      cp .env.local .env &&
      composer install &&
      php artisan storage:link &&
      php-fpm"
    volumes:
      - ./services/pyramid/storage/app:/var/www/storage/app

  queue:
    build: ./services/pyramid
    container_name: dev-pyramid-queue
    depends_on:
      - app
    restart: unless-stopped
    command: >
      bash -c "mkdir -p storage/framework/{sessions,views,cache} &&
      cp .env.local .env &&
      composer install &&
      /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf"

  web_server:
    build:
      context: ./services/pyramid
      dockerfile: nginx.Dockerfile
    container_name: dev-pyramid-webserver
    restart: unless-stopped
    tty: true
    depends_on:
      - app
    ports:
      - "8000:8000"
    volumes:
      - ./services/pyramid/storage/app/public:/var/www/public/storage

  frankenphp:
    build:
      context: .
    entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=1
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  merchant-bff:
    build: ./services/merchant-bff
    container_name: merchant-bff
    depends_on:
      - app
    restart: unless-stopped
    tty: true
    develop:
      watch:
        - action: sync
          path: ./services/merchant-bff
          target: /app
          ignore:
            - /merchant-bff/vendor
        - action: sync+restart
          path: ./services/merchant-bff/composer.json
          target: /app/composer.json
    command: >
      bash -c "mkdir -p storage/framework/{sessions,views,cache} &&
      cp .env.local .env &&
      composer install &&
      php artisan storage:link &&
      php-fpm"
    volumes:
      - ./services/merchant-bff/storage/app:/var/www/storage/app
